---
alias: Sonos - Playlist - 102.7 KIIS-FM Los Angeles
description: Play 102.7 KIIS-FM Los Angeles on Sonos
id: 102_7_KIIS_FM_Los_Angeles
trigger:
  - platform: webhook
    webhook_id: sonos_102_7_KIIS_FM_Los_Angeles
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "102.7 KIIS-FM Los Angeles"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "102.7 KIIS-FM Los Angeles"
