---
alias: Sonos - Playlist - 1170 SEN
description: Play 1170 SEN on Sonos
id: 1170_SEN
trigger:
  - platform: webhook
    webhook_id: sonos_1170_SEN
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "1170 SEN"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "1170 SEN"
