---
alias: "[Sonos, Playlist] 1-Playlist"
description: Play 1-Playlist on Sonos
id: 1_Playlist
trigger:
  - platform: webhook
    webhook_id: sonos_1_Playlist
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "1-Playlist"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "1-Playlist"
