---
alias: Sonos - Playlist - 93.5 Triple M Dubbo
description: Play 93.5 Triple M Dubbo on Sonos
id: 93_5_Triple_M_Dubbo
trigger:
  - platform: webhook
    webhook_id: sonos_93_5_Triple_M_Dubbo
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "93.5 Triple M Dubbo"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "93.5 Triple M Dubbo"
