---
alias: Sonos - Playlist - ABC New England North West
description: Play ABC New England North West on Sonos
id: ABC_New_England_North_West
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_New_England_North_West
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC New England North West"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ABC New England North West"
