---
alias: Sonos - Playlist - ABC News
description: Play ABC News on Sonos
id: ABC_News
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_News
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC News"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ABC News"
