---
alias: "[Sonos, Playlist] ABC Radio Sydney"
description: Play ABC Radio Sydney on Sonos
id: ABC_Radio_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_Radio_Sydney
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Radio Sydney"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ABC Radio Sydney"
