---
alias: "[Sonos, Playlist] ABC Sport"
description: Play ABC Sport on Sonos
id: ABC_Sport
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_Sport
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Sport"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ABC Sport"
