---
alias: Sonos - Playlist - Absolute Radio 90s
description: Play Absolute Radio 90s on Sonos
id: Absolute_Radio_90s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_90s
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 90s"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Absolute Radio 90s"
