---
alias: "[Sonos, Playlist] Absolute Radio 00s"
description: Play Absolute Radio 00s on Sonos
id: Absolute_Radio_00s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_00s
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 00s"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Absolute Radio 00s"
