---
alias: "[Sonos, Playlist] Absolute Radio UK (AAC)"
description: Play Absolute Radio UK (AAC) on Sonos
id: Absolute_Radio_UK_AAC
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_UK_AAC
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio UK (AAC)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Absolute Radio UK (AAC)"
