---
alias: "[Sonos, Playlist] BBC World Service News"
description: Play BBC World Service News on Sonos
id: BBC_World_Service_News
trigger:
  - platform: webhook
    webhook_id: sonos_BBC_World_Service_News
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC World Service News"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "BBC World Service News"
