---
alias: "[Sonos, Playlist] Capital London"
description: Play Capital London on Sonos
id: Capital_London
trigger:
  - platform: webhook
    webhook_id: sonos_Capital_London
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Capital London"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Capital London"
