---
alias: Sonos - Playlist - CNN International
description: Play CNN International on Sonos
id: CNN_International
trigger:
  - platform: webhook
    webhook_id: sonos_CNN_International
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "CNN International"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "CNN International"
