---
alias: Sonos - Playlist - COVID-19 Social Distancing Sucks
description: Play COVID-19 Social Distancing Sucks on Sonos
id: COVID_19_Social_Distancing_Sucks
trigger:
  - platform: webhook
    webhook_id: sonos_COVID_19_Social_Distancing_Sucks
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "COVID-19 Social Distancing Sucks"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "COVID-19 Social Distancing Sucks"
