---
alias: "[Sonos, Playlist] Double J (Sydney, NSW)"
description: Play Double J (Sydney, NSW) on Sonos
id: Double_J_Sydney_NSW
trigger:
  - platform: webhook
    webhook_id: sonos_Double_J_Sydney_NSW
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Double J (Sydney, NSW)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Double J (Sydney, NSW)"
