---
alias: Sonos - Playlist - ESPN Radio
description: Play ESPN Radio on Sonos
id: ESPN_Radio
trigger:
  - platform: webhook
    webhook_id: sonos_ESPN_Radio
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ESPN Radio"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ESPN Radio"
