---
alias: "[Sonos, Playlist] Gaydio (Manchester) (Dance & Electronic)"
description: Play Gaydio (Manchester) (Dance & Electronic) on Sonos
id: Gaydio_Manchester_Dance_Electronic
trigger:
  - platform: webhook
    webhook_id: sonos_Gaydio_Manchester_Dance_Electronic
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Gaydio (Manchester) (Dance & Electronic)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Gaydio (Manchester) (Dance & Electronic)"
