---
alias: "[Sonos, Playlist] Gaydio (London) (Top 40 & Pop Music)"
description: Play Gaydio (London) (Top 40 & Pop Music) on Sonos
id: Gaydio_London_Top_40_Pop_Music
trigger:
  - platform: webhook
    webhook_id: sonos_Gaydio_London_Top_40_Pop_Music
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Gaydio (London) (Top 40 & Pop Music)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Gaydio (London) (Top 40 & Pop Music)"
