---
alias: "[Sonos, Playlist] GOLD 104.3"
description: Play GOLD 104.3 on Sonos
id: GOLD_104_3
trigger:
  - platform: webhook
    webhook_id: sonos_GOLD_104_3
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "GOLD 104.3"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "GOLD 104.3"
