---
alias: "[Sonos, Playlist] MSNBC"
description: Play MSNBC on Sonos
id: MSNBC
trigger:
  - platform: webhook
    webhook_id: sonos_MSNBC
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "MSNBC"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "MSNBC"
