---
alias: "[Sonos, Playlist] Nova Nation"
description: Play Nova Nation on Sonos
id: Nova_Nation
trigger:
  - platform: webhook
    webhook_id: sonos_Nova_Nation
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova Nation"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova Nation"
