---
alias: Sonos - Playlist - Playlists
description: Play Playlists on Sonos
id: Playlists
trigger:
  - platform: webhook
    webhook_id: sonos_Playlists
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Playlists"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Playlists"
