---
alias: "[Sonos, Playlist] Radio X Classic Rock (Classic Rock)"
description: Play Radio X Classic Rock (Classic Rock) on Sonos
id: Radio_X_Classic_Rock_Classic_Rock
trigger:
  - platform: webhook
    webhook_id: sonos_Radio_X_Classic_Rock_Classic_Rock
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Radio X Classic Rock (Classic Rock)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Radio X Classic Rock (Classic Rock)"
