---
alias: Sonos - Playlist - Radio X
description: Play Radio X on Sonos
id: Radio_X
trigger:
  - platform: webhook
    webhook_id: sonos_Radio_X
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Radio X"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Radio X"
