---
alias: "[Sonos, Playlist] Sky News Radio"
description: Play Sky News Radio on Sonos
id: Sky_News_Radio
trigger:
  - platform: webhook
    webhook_id: sonos_Sky_News_Radio
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Sky News Radio"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Sky News Radio"
