---
alias: "[Sonos, Playlist] talkSPORT"
description: Play talkSPORT on Sonos
id: talkSPORT
trigger:
  - platform: webhook
    webhook_id: sonos_talkSPORT
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "talkSPORT"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "talkSPORT"
