---
alias: "[Sonos, Playlist] talkSPORT 2 (Sports Talk & News)"
description: Play talkSPORT 2 (Sports Talk & News) on Sonos
id: talkSPORT_2_Sports_Talk_News
trigger:
  - platform: webhook
    webhook_id: sonos_talkSPORT_2_Sports_Talk_News
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "talkSPORT 2 (Sports Talk & News)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "talkSPORT 2 (Sports Talk & News)"
