---
alias: Sonos - Playlist - Tamworth's 88.9FM
description: Play Tamworth's 88.9FM on Sonos
id: Tamworth_s_88_9FM
trigger:
  - platform: webhook
    webhook_id: sonos_Tamworth_s_88_9FM
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Tamworth's 88.9FM"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Tamworth's 88.9FM"
