---
alias: Sonos - Playlist - The Hits Auckland 97.4 (World Music)
description: Play The Hits Auckland 97.4 (World Music) on Sonos
id: The_Hits_Auckland_97_4_World_Music
trigger:
  - platform: webhook
    webhook_id: sonos_The_Hits_Auckland_97_4_World_Music
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "The Hits Auckland 97.4 (World Music)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "The Hits Auckland 97.4 (World Music)"
