---
alias: Sonos - Playlist - The Rock 90.2 (Rock Music)
description: Play The Rock 90.2 (Rock Music) on Sonos
id: The_Rock_90_2_Rock_Music
trigger:
  - platform: webhook
    webhook_id: sonos_The_Rock_90_2_Rock_Music
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "The Rock 90.2 (Rock Music)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "The Rock 90.2 (Rock Music)"
