---
alias: Sonos - Playlist - Triple M 80s (Sydney)
description: Play Triple M 80s (Sydney) on Sonos
id: Triple_M_80s_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_80s_Sydney
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 80s (Sydney)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple M 80s (Sydney)"
