---
alias: "[Sonos, Playlist] Triple J Hottest"
description: Play Triple J Hottest on Sonos
id: Triple_J_Hottest
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_J_Hottest
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple J Hottest"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple J Hottest"
