---
alias: Sonos - Playlist - TripleM 2000s
description: Play TripleM 2000s on Sonos
id: TripleM_2000s
trigger:
  - platform: webhook
    webhook_id: sonos_TripleM_2000s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "TripleM 2000s"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "TripleM 2000s"
