---
alias: "[Sonos, Playlist] Triple M 104.9 Sydney"
description: Play Triple M 104.9 Sydney on Sonos
id: Triple_M_104_9_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_104_9_Sydney
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 104.9 Sydney"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple M 104.9 Sydney"
