---
alias: "[Sonos, Playlist] Triple M Classic Rock Digital (Sydney)"
description: Play Triple M Classic Rock Digital (Sydney) on Sonos
id: Triple_M_Classic_Rock_Digital_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_Classic_Rock_Digital_Sydney
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M Classic Rock Digital (Sydney)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple M Classic Rock Digital (Sydney)"
