---
alias: Sonos - Playlist - Triple M 105.1 Melbourne
description: Play Triple M 105.1 Melbourne on Sonos
id: Triple_M_105_1_Melbourne
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_105_1_Melbourne
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 105.1 Melbourne"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple M 105.1 Melbourne"
