---
alias: "[Sonos, Playlist] Triple M Hard n Heavy (Sydney)"
description: Play Triple M Hard n Heavy (Sydney) on Sonos
id: Triple_M_Hard_n_Heavy_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_Hard_n_Heavy_Sydney
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M Hard n Heavy (Sydney)"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple M Hard n Heavy (Sydney)"
