---
alias: Sonos - Playlist - Virgin Radio Chilled UK
description: Play Virgin Radio Chilled UK on Sonos
id: Virgin_Radio_Chilled_UK
trigger:
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_Chilled_UK
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio Chilled UK"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Virgin Radio Chilled UK"
