---
alias: "[Sonos, Playlist] Virgin Radio Anthems UK"
description: Play Virgin Radio Anthems UK on Sonos
id: Virgin_Radio_Anthems_UK
trigger:
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_Anthems_UK
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio Anthems UK"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Virgin Radio Anthems UK"
