---
waste_collection_schedule:
  sources:
    - args:
        frequency: WEEKLY
        interval: 1
        type: General Garbage
        weekdays: TH
      calendar_title: garbage
      customize:
        - alias: General Garbage
          icon: mdi:delete
          type: garbage
      name: static
    - args:
        frequency: WEEKLY
        interval: 2
        start: "2023-11-23"
        type: Green Waste
        weekdays: TH
      calendar_title: greenwaste
      customize:
        - alias: Green Waste
          icon: mdi:tree-outline
          type: greenwaste
      name: static
    - args:
        frequency: WEEKLY
        interval: 2
        start: "2023-11-30"
        type: Recycling
        weekdays: TH
      calendar_title: recycling
      customize:
        - alias: Recycling
          icon: mdi:recycle
          type: recycling
      name: static # - name: ics
    #   args:
    #     file: /config/bin_schedule.ics

sensor:
  - add_days_to: true
    details_format: generic
    name: "[Next Bin Day] Garbage (Red Bin)"
    platform: waste_collection_schedule
    source_index: 0
    types:
      - General Garbage
    value_template: "{{ value.daysTo }}"
  - add_days_to: true
    details_format: generic
    name: "[Next Bin Day] Greenwaste (Green Bin)"
    platform: waste_collection_schedule
    source_index: 1
    types:
      - Green Waste
    value_template: "{{ value.daysTo }}"
  - add_days_to: true
    details_format: generic
    name: "[Next Bin Day] Recycling (Yellow Bin)"
    platform: waste_collection_schedule
    source_index: 2
    types:
      - Recycling
    value_template: "{{ value.daysTo }}"
