resource: http://192.168.1.65:9090/api/v1/query?query=readsb_aircraft_total
sensor:
  name: flighttracker_aircraft_total
  unique_id: flighttracker_aircraft_total
  value_template: >
    {{ value_json.data.result[0].value[1] }}
  unit_of_measurement: aircraft
  state_class: measurement
  icon: mdi:airplane-alert
scan_interval: 10
