- id: '1670914225475'
  alias: PiLocator Alerts
  description: ''
  use_blueprint:
    path: giqcass/rpilocator-notification-blueprint.yaml
    input:
      zero_2_w: --NO--
      notify_device: e93f101330f503133307ec86a813b514
      cm4_mmc: MMC
      cm4_wifi: With Wifi
