- id: '1664679805983'
  alias: Hook - Media Player
  description: ''
  use_blueprint:
    path: EPMatt/media_player.yaml
    input:
      controller_device: 60c680d2da19565a2feafe27325f13ed
      controller_entity: media_
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      media_player: media_player.office_sonos
- id: '1670914225475'
  alias: PiLocator Alerts
  description: ''
  use_blueprint:
    path: giqcass/rpilocator-notification-blueprint.yaml
    input:
      zero_2_w: --NO--
      notify_device: 9e09ff6838383746ba31fe9914a10e47
      cm4_mmc: MMC
      cm4_wifi: With Wifi
- id: '1695121244822'
  alias: Alarm test
  description: ''
  trigger: []
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.bedroom_symfonisk
    data:
      media_content_id: FV:2/17
      media_content_type: favorite_item_id
    metadata:
      title: Double J (Sydney, NSW)
      thumbnail: http://d1flk301fokgs0.cloudfront.net/cachedImages/F899781C488DFE0B7671CAE0B7A3C203_180.jpg
      media_class: genre
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: favorites
        media_content_id: ''
      - media_content_type: favorites_folder
        media_content_id: object.item.audioItem.audioBroadcast
  - service: media_player.volume_set
    data:
      volume_level: 0.15
    target:
      entity_id: media_player.bedroom_symfonisk
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.bedroom_symfonisk
  - service: light.toggle
    data: {}
    target:
      entity_id: light.bedroom_lamp
  mode: single
