- id: '1670914225475'
  alias: PiLocator Alerts
  description: ''
  use_blueprint:
    path: giqcass/rpilocator-notification-blueprint.yaml
    input:
      zero_2_w: --NO--
      notify_device: 9e09ff6838383746ba31fe9914a10e47
      cm4_mmc: MMC
      cm4_wifi: With Wifi
