- id: '1670914225475'
  alias: PiLocator Alerts
  description: ''
  use_blueprint:
    path: giqcass/rpilocator-notification-blueprint.yaml
    input:
      zero_2_w: --NO--
      notify_device: 9e09ff6838383746ba31fe9914a10e47
      cm4_mmc: MMC
      cm4_wifi: With Wifi
- id: '1695121244822'
  alias: '[Alarm Clock] Testing'
  description: ''
  trigger: []
  condition: []
  action:
  - variables:
      sonos_device: media_player.bedroom_symfonisk
      light_switchedon: light.bedroom_lamp
      music_selected: '{{states(''input_select.alarm_music'')}}'
  - service: media_player.select_source
    data:
      entity_id: '{{sonos_device}}'
      source: '{{music_selected}}'
  - service: media_player.volume_set
    data:
      volume_level: 0.15
    target:
      entity_id: '{{sonos_device}}'
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: '{{sonos_device}}'
  - service: light.toggle
    data: {}
    target:
      entity_id: '{{light_switchedon}}'
  mode: single
- id: '1695195690273'
  alias: '[Alarm Clock] Set Wakeup Music Select'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.sonos_favorites
    to:
  condition: []
  action:
  - variables:
      sonos_favourites: '{{ state_attr(''sensor.sonos_favorites'', ''items'').values()
        | list }}'
      current_favourite: '{{states(''input_select.alarm_music'')}}'
  - service: input_select.set_options
    data:
      options: '{{sonos_favourites}}'
    target:
      entity_id: input_select.alarm_music
  - service: input_select.select_option
    data:
      option: '{{current_favourite}}'
    target:
      entity_id: input_select.alarm_music
  mode: single
