---
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  - platform: event
    event_type: event_template_reloaded
action:
  - service: weather.get_forecasts
    data:
      type: hourly
    target:
      entity_id: weather.openweathermap
    response_variable: forecast_hourly
sensor:
  - name: "[Weather Forecast] OpenWeatherMap (Hourly)"
    unique_id: weather_forecast_openweathermap_hourly
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ forecast_hourly }}"
      category: weatherforecast
      provider: OpenWeatherMap
