---
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  - platform: event
    event_type: event_template_reloaded
action:
  - service: weather.get_forecasts
    data:
      type: daily
    target:
      entity_id: weather.pirateweather
    response_variable: forecast_daily
  - service: weather.get_forecasts
    data:
      type: hourly
    target:
      entity_id: weather.pirateweather
    response_variable: forecast_hourly
sensor:
  - name: "[Weather Forecast] Pirate Weather (Daily)"
    unique_id: weather_forecast_pirateweather_daily
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ forecast_daily }}"
      category: weatherforecast
      provider: Pirate Weather
  - name: "[Weather Forecast] Pirate Weather (Hourly)"
    unique_id: weather_forecast_pirateweather_hourly
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ forecast_hourly }}"
      category: weatherforecast
      provider: Pirate Weather
