---
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /3
  - platform: event
    event_type: event_template_reloaded
action:
  - service: weather.get_forecast
    data:
      type: daily
    target:
      entity_id: weather.forecast_home
    response_variable: forecast_daily
  - service: weather.get_forecast
    data:
      type: daily
    target:
      entity_id: weather.forecast_home
    response_variable: forecast_hourly
sensor:
  - name: "[Weather Forecast] Yr.No Daily"
    unique_id: weather_forecast_yrno_daily
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ forecast_daily.forecast }}"
      category: weatherforecast
      provider: Yr.No
  - name: "[Weather Forecast] Yr.No Hourly"
    unique_id: weather_forecast_yrno_hourly
    state: "{{ now().isoformat() }}"
    attributes:
      forecast: "{{ forecast_hourly.forecast }}"
      category: weatherforecast
      provider: Yr.No
