---
id: logs_critical_counter_increment
alias: Logs - Increment Critical Counter
mode: parallel
max: 50
trigger:
  platform: event
  event_type: system_log_event
  event_data:
    level: CRITICAL
action:
  service: counter.increment
  entity_id: counter.logs_critical_counter
