---
id: logs_error_counter_increment
alias: Logs - Increment Error Counter
mode: parallel
max: 50
trigger:
  platform: event
  event_type: system_log_event
  event_data:
    level: ERROR
condition:
  - condition: template
    value_template: "{{ not 'logs_error_counter_increment' in (trigger.event.data.message|string) }}"
action:
  service: counter.increment
  entity_id: counter.logs_error_counter
