---
id: logs_warning_counter_increment
alias: Logs - Increment Warning Counter
mode: parallel
max: 50
trigger:
  platform: event
  event_type: system_log_event
  event_data:
    level: WARNING
action:
  service: counter.increment
  entity_id: counter.logs_warning_counter
