---
resource: https://site.web.api.espn.com/apis/v2/sports/soccer/fra.1/standings
sensor:
  name: scoreboard_lig1
  value_template: "{{ now() }}"
  json_attributes_path: "$['children'][0]['standings']"
  json_attributes:
    - entries
scan_interval: 3600
