---
resource: https://site.web.api.espn.com/apis/v2/sports/rugby/242041/standings
sensor:
  name: scoreboard_srp
  value_template: "{{ now() }}"
  json_attributes_path: "$['children'][0]['standings']"
  json_attributes:
    - entries
scan_interval: 21600
