---
resource: https://site.web.api.espn.com/apis/v2/sports/basketball/nbl/standings?type=0&level=4
sensor:
  name: scoreboard_nbl
  value_template: "{{ now() }}"
  json_attributes_path: "$['standings']"
  json_attributes:
    - entries
scan_interval: 3600
