---
resource: https://site.web.api.espn.com/apis/v2/sports/soccer/ita.1/standings
sensor:
  name: scoreboard_sea
  value_template: "{{ now() }}"
  json_attributes_path: "$['children'][0]['standings']"
  json_attributes:
    - entries
scan_interval: 3600
