---
resource: https://site.web.api.espn.com/apis/v2/sports/baseball/mlb/standings?seasontype=2&type=0&level=4
sensor:
  name: scoreboard_mlb
  value_template: "{{ now() }}"
  json_attributes:
    - children
scan_interval: 3600
