---
resource: https://site.web.api.espn.com/apis/v2/sports/hockey/nhl/standings?type=0&level=4
sensor:
  name: scoreboard_nhl
  value_template: "{{ now() }}"
  json_attributes:
    - children
scan_interval: 3600
