---
id: "pyscript_getdata_untappd"
alias: "[PyScript] GetData: Untappd"
description: "[PyScript] GetData: Untappd"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/3"
condition: []
action:
  - service: pyscript.getdata_untappd_project52
mode: single
