---
alias: "[Weather] Lightning Notification"
id: weather_lightningnotification
mode: single

trigger:
  - platform: state
    entity_id: sensor.weatherflow_forecast_lightnings_strikes

condition:
  - condition: numeric_state
    entity_id: sensor.weatherflow_forecast_distance_last_lightning_strike
    below: 10

action:
  - service: notify.alert
    data:
      title: Weather Alert
      message: Lightning within 10km of home!
      data:
        tag: "weather-lightning"
        subtitle: "⚡️ Lightning within 10km ⚡"
