---
sensor:
  name: udm_unifios
  unique_id: udm_unifios
  command: |-
    python3 << EOF
    import json, yaml, requests
    from datetime import datetime
    from urllib3 import disable_warnings
    disable_warnings()

    SECRETS_FILE = "/config/secrets.yaml"
    def get_secret(secret):
        try:
            with open(SECRETS_FILE, "r", encoding="utf8") as file:
                secrets = yaml.full_load(file)
                for key, value in secrets.items():
                    if key == secret:
                        return value
        except FileNotFoundError:
            print("secrets.yaml not found")
            exit()

    IP = get_secret("unifi_ipaddress")
    PORT = get_secret("unifi_port")
    USER = get_secret("unifi_user2")
    PASS = get_secret("unifi_pass2")
    URL = f"https://{IP}:{PORT}"

    login = requests.request("POST", f"{URL}/api/auth/login", \
        headers={"Content-Type": "application/json"}, \
        data=json.dumps({"username": USER, "password": PASS}), verify=False)
    response = requests.request("GET", f"{URL}/proxy/network/api/s/default/stat/device/", \
        cookies=login.cookies, verify=False)
    data = response.json()["data"][0]

    print(json.dumps({
        "cpu": data["system-stats"]["cpu"],
        "cpu_temp": round(data["temperatures"][1]["value"], 1),
        "system_temp": round(data["temperatures"][0]["value"], 1),
        "memory": data["system-stats"]["mem"],
        "disk": round(data["storage"][1]["used"] / data["storage"][1]["size"] * 100, 1),
        "internet": data["wan1"]["up"],
        "uptime": datetime.fromtimestamp(data["startup_timestamp"]).isoformat(),
        "availability": data["uptime_stats"]["WAN"]["availability"],
        "average_latency": data["uptime_stats"]["WAN"]["latency_average"],
        "down": data["uplink"]["rx_rate"] / 1000000,
        "up": data["uplink"]["tx_rate"] / 1000000,
        "version": data["displayable_version"],
        "last_wan_ip": data["last_wan_ip"]
    }))
    EOF
  command_timeout: 180
  value_template: |
    {{ value_json.internet | lower }}
  json_attributes:
    - cpu
    - cpu_temp
    - system_temp
    - memory
    - disk
    - internet
    - uptime
    - availability
    - average_latency
    - down
    - up
    - version
    - last_wan_ip
  scan_interval: 900
