---
id: notifications_save_on_create
alias: "Notifications: Save on Create"
mode: queued
initial_state: true
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: create
condition:
  - condition: template
    value_template: >-
      {{ trigger.event.data.service_data.notification_id != "config_entry_discovery" }}
action:
  - service: mqtt.publish
    data:
      topic: "home-assistant/notifications/{{ trigger.event.data.service_data.notification_id }}"
      payload: >-
        {
          "notification_id" : "{{ trigger.event.data.service_data.notification_id }}",
          "title" : "{{ trigger.event.data.service_data.title }}",
          "message" : {{ trigger.event.data.service_data.message | to_json}}
        }
      retain: true
