---
alias: "[Addon Watchguard] Sungather"
description: ""
trigger:
  - platform: time_pattern
    minutes: "*"
condition:
  - condition: state
    entity_id: binary_sensor.sungather_running
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
action:
  - repeat:
      until:
        - condition: state
          entity_id: binary_sensor.sungather_running
          state: "on"
          for:
            hours: 0
            minutes: 5
            seconds: 0
      sequence:
        - if:
            - condition: state
              entity_id: binary_sensor.sungather_running
              state: "off"
          then:
            - service: hassio.addon_start
              data:
                addon: 7b536ee6_sungather
            - delay:
                hours: 0
                minutes: 1
                seconds: 0
                milliseconds: 0
            - service: homeassistant.update_entity
              data: {}
              target:
                entity_id: binary_sensor.sungather_running
          else:
            - delay:
                hours: 0
                minutes: 0
                seconds: 30
                milliseconds: 0
            - service: homeassistant.update_entity
              data: {}
              target:
                entity_id: binary_sensor.sungather_running
mode: single
