---
binary_sensor:
  - name: "alerts_wan_offline"
    unique_id: alert_wan_offline
    icon: mdi:wan
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.connected_wan','off')
          and is_state('input_boolean.alerts_network','on') }}
    attributes:
      category: network

  - name: "alerts_backup"
    unique_id: alerts_backup
    icon: mdi:cloud-upload-outline
    device_class: problem
    delay_on: 60
    state: >
      {% if is_state('input_boolean.alerts_ha','on') %}
        {{ states('sensor.backup_size_status') in ['severe','critical','error']
            or is_state('binary_sensor.home_assistant_google_drive_backup_running','off') }}
      {% endif %}
    attributes:
      category: homeassistant

  - name: "alerts_connect_weatherflow_cloud"
    unique_id: alerts_connect_weatherflow_cloud
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.connected_weatherflow_cloud','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_weatherflow_local"
    unique_id: alerts_connect_weatherflow_local
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.connected_weatherflow_local','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_pirateweather"
    unique_id: alerts_connect_pirateweather
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.connected_pirateweather','off')
          and is_state('input_boolean.alerts_weather','on') }}

  - name: "alerts_connect_openuv"
    unique_id: alerts_connect_openuv
    icon: mdi:weather-sunny-alert
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_openuv','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_waqi"
    unique_id: alerts_connect_wqai
    icon: mdi:smog
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_waqi','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_docker_sungather"
    unique_id: alerts_docker_sungather
    icon: mdi:docker
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_docker_sungather','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_docker_weatherflow2mqtt"
    unique_id: alerts_docker_weatherflow2mqtt
    icon: mdi:docker
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_docker_weatherflow2mqtt','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_adguard"
    unique_id: alerts_connect_adguard
    icon: mdi:shield_account
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_adguard','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_apple_tv"
    unique_id: alerts_connect_apple_tv
    icon: mdi:apple
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_apple_tv','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_bureau_of_meteorology"
    unique_id: alerts_connect_bureau_of_meteorology
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_bureau_of_meteorology','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_eufy_security"
    unique_id: alerts_connect_eufy_security
    icon: mdi:cctv-off
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_eufy_security','off')
          and is_state('input_boolean.alerts_camera','on') }}
    attributes:
      category: camera

  - name: "alerts_connect_hdhomerun"
    unique_id: alerts_connect_hdhomerun
    icon: mdi:television-box
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_hdhomerun','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_lg_smartthinq"
    unique_id: alerts_connect_lg_smartthinq
    icon: si:lg
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_lg_smartthinq','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_solcast_solar"
    unique_id: alerts_connect_solcast_solar
    icon: mdi:solar-power-variant
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_solcast_solar','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_spotify"
    unique_id: alerts_connect_spotify
    icon: mdi:spotify
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_spotify','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_synology"
    unique_id: alerts_connect_synology
    icon: mdi:nas
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_synology','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_unifi"
    unique_id: alerts_connect_unifi
    icon: mdi:wifi
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_unifi','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_connect_speedtest"
    unique_id: alerts_connect_speedtest
    icon: mdi:speedometer
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.connected_speedtest','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alert_nabucasa_remoteui"
    unique_id: alert_nabucasa_remoteui
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.remote_ui','off')
          and is_state('input_boolean.alerts_ha','on')
          and is_state('input_boolean.ha_startup_pending','off') }}
    attributes:
      category: homeassistant

  - name: "alerts_docker_containersoff"
    unique_id: alerts_docker_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 300
    state: >
      {{ (is_state('binary_sensor.docker_tbsh1_containersoff','on')
          or is_state('binary_sensor.docker_tbsh2_containersoff','on')
          or is_state('binary_sensor.docker_tbsh3_containersoff','on')
          or is_state('binary_sensor.docker_tbsh5_containersoff','on')
          or is_state('binary_sensor.docker_pi4srv_containersoff','on'))
          and is_state('input_boolean.alerts_docker_containers_off','on') }}
    attributes:
      category: docker
