---
sensor:
  - name: stats_docker
    unique_id: stats_docker
    icon: mdi:docker
    state: >
      {{ states('sensor.tbsh3_monitordocker_containers_total') | int(default=0)
        + states('sensor.tbsh1_monitordocker_containers_total') | int(default=0)
        + states('sensor.tbsh2_monitordocker_containers_total') | int(default=0)
        + states('sensor.tbsh5_monitordocker_containers_total') | int(default=0)
        + states('sensor.pi4srv_monitordocker_containers_total') | int(default=0)}}
    state_class: measurement
    unit_of_measurement: Containers
    attributes:
      containers_running: >
        {{ states('sensor.tbsh3_monitordocker_containers_running') | int(default=0)
          + states('sensor.tbsh1_monitordocker_containers_running') | int(default=0)
          + states('sensor.tbsh2_monitordocker_containers_running') | int(default=0)
          + states('sensor.tbsh5_monitordocker_containers_running') | int(default=0)
          + states('sensor.pi4srv_monitordocker_containers_running') | int(default=0) }}
      containers_stopped: >
        {{ states('sensor.tbsh3_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.tbsh1_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.tbsh2_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.tbsh5_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.pi4srv_monitordocker_containers_stopped') | int(default=0) }}
      images: >
        {{ states('sensor.tbsh3_monitordocker_images') | int(default=0)
          + states('sensor.tbsh1_monitordocker_images') | int(default=0)
          + states('sensor.tbsh2_monitordocker_images') | int(default=0)
          + states('sensor.tbsh5_monitordocker_images') | int(default=0)
          + states('sensor.pi4srv_monitordocker_images') | int(default=0) }}
      containers_updatable: >
        {{ states.update | selectattr('state', 'eq', 'on') | selectattr('entity_id','search','update.wud_*') | list | count }}

binary_sensor:
  - name: updates_docker
    unique_id: updates_docker
    icon: mdi:docker
    state: >
      {{ states.update  | selectattr('state', 'eq', 'on')  | selectattr('entity_id','search','wud_*') |list|count|int(-1) > 0 }}
    attributes:
      details: >
        {%- for upd in states.update | selectattr('state', 'eq', 'on')  | selectattr('entity_id','search','wud_*') | sort(attribute="attributes.friendly_name") | list %}
        * {{upd.attributes.friendly_name}} ({{upd.attributes.image_name}}): {{upd.attributes.installed_version}} > {{upd.attributes.latest_version}}
        {%- endfor %}
      availability: >
        {{ states.update  | selectattr('state', 'eq', 'on')  | selectattr('entity_id','search','wud_*') |list|count|int(-1) > 0 }}
