---
sensor:
  - name: stats_docker
    unique_id: stats_docker
    icon: mdi:docker
    state: >
      {{ states('sensor.tbsh03_monitordocker_containers_total') | int
        + states('sensor.tbsh1_monitordocker_containers_total') | int
        + states('sensor.pi4srv_monitordocker_containers_total') | int }}
    state_class: measurement
    unit_of_measurement: Containers
    attributes:
      containers_running: >
        {{ states('sensor.tbsh03_monitordocker_containers_running') | int
          + states('sensor.tbsh1_monitordocker_containers_running') | int
          + states('sensor.pi4srv_monitordocker_containers_running') | int }}
      containers_stopped: >
        {{ states('sensor.tbsh03_monitordocker_containers_stopped') | int
          + states('sensor.tbsh1_monitordocker_containers_stopped') | int
          + states('sensor.pi4srv_monitordocker_containers_stopped') | int }}
      images: >
        {{ states('sensor.tbsh03_monitordocker_images') | int
          + states('sensor.tbsh1_monitordocker_images') | int
          + states('sensor.pi4srv_monitordocker_images') | int }}
