---
sensor:
  - name: stats_docker
    unique_id: stats_docker
    icon: mdi:docker
    state: >
      {{ states('sensor.tbsh3_monitordocker_containers_total') | int(default=0)
        + states('sensor.tbsh1_monitordocker_containers_total') | int(default=0)
        + states('sensor.tbsh2_monitordocker_containers_total') | int(default=0)
        + states('sensor.tbsh5_monitordocker_containers_total') | int(default=0)
        + states('sensor.pi4srv_monitordocker_containers_total') | int(default=0)}}
    state_class: measurement
    unit_of_measurement: Containers
    attributes:
      containers_running: >
        {{ states('sensor.tbsh3_monitordocker_containers_running') | int(default=0)
          + states('sensor.tbsh1_monitordocker_containers_running') | int(default=0)
          + states('sensor.tbsh2_monitordocker_containers_running') | int(default=0)
          + states('sensor.tbsh5_monitordocker_containers_running') | int(default=0)
          + states('sensor.pi4srv_monitordocker_containers_running') | int(default=0) }}
      containers_stopped: >
        {{ states('sensor.tbsh3_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.tbsh1_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.tbsh2_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.tbsh5_monitordocker_containers_stopped') | int(default=0)
          + states('sensor.pi4srv_monitordocker_containers_stopped') | int(default=0) }}
      images: >
        {{ states('sensor.tbsh3_monitordocker_images') | int(default=0)
          + states('sensor.tbsh1_monitordocker_images') | int(default=0)
          + states('sensor.tbsh2_monitordocker_images') | int(default=0)
          + states('sensor.tbsh5_monitordocker_images') | int(default=0)
          + states('sensor.pi4srv_monitordocker_images') | int(default=0) }}
      containers_updatable: >
        {{ states.update | selectattr('state', 'eq', 'on') | selectattr('entity_id','search','update.wud_*') | list | count }}

binary_sensor:
  - name: updates_docker
    unique_id: updates_docker
    icon: mdi:docker
    state: >
      {{ states.update  | selectattr('state', 'eq', 'on')  | selectattr('entity_id','search','wud_*') |list|count|int(-1) > 0 }}
    attributes:
      details: >
        {%- for upd in states.update | selectattr('state', 'eq', 'on')  | selectattr('entity_id','search','wud_*') | sort(attribute="attributes.friendly_name") | list %}
        * {{upd.attributes.friendly_name}} ({{upd.attributes.image_name}}): {{upd.attributes.installed_version}} > {{upd.attributes.latest_version}}
        {%- endfor %}
      availability: >
        {{ states.update  | selectattr('state', 'eq', 'on')  | selectattr('entity_id','search','wud_*') |list|count|int(-1) > 0 }}

  - name: "docker_tbsh1_containersoff"
    unique_id: docker_tbsh1_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 60
    state: >
      {{states.switch
        |selectattr('state', 'eq', 'off')
        |selectattr('entity_id','search','tbsh1_*')
        |list|count|int(-1) }}
    attributes:
      containers: >
        {{ states.switch
          |selectattr('state', 'eq', 'off')
          |selectattr('entity_id','search','tbsh1_*')
          |map(attribute='name')|join(', ') }}
      category: docker
      availability: >
        {{ states.switch
        |selectattr('state', 'eq', 'on')
        |selectattr('entity_id','search','tbsh1_*')
        |list|count|int(-1) > 0 }}

  - name: "docker_tbsh2_containersoff"
    unique_id: docker_tbsh2_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 60
    state: >
      {{states.switch
        |selectattr('state', 'eq', 'off')
        |selectattr('entity_id','search','tbsh2_*')
        |list|count|int(-1) }}
    attributes:
      containers: >
        {{ states.switch
          |selectattr('state', 'eq', 'off')
          |selectattr('entity_id','search','tbsh2_*')
          |map(attribute='name')|join(', ') }}
      category: docker
      availability: >
        {{ states.switch
        |selectattr('state', 'eq', 'on')
        |selectattr('entity_id','search','tbsh2_*')
        |list|count|int(-1) > 0 }}

  - name: "docker_tbsh3_containersoff"
    unique_id: docker_tbsh3_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 60
    state: >
      {{states.switch
        |selectattr('state', 'eq', 'off')
        |selectattr('entity_id','search','tbsh3_*')
        |list|count|int(-1) }}
    attributes:
      containers: >
        {{ states.switch
          |selectattr('state', 'eq', 'off')
          |selectattr('entity_id','search','tbsh3_*')
          |map(attribute='name')|join(', ') }}
      category: docker
      availability: >
        {{ states.switch
        |selectattr('state', 'eq', 'on')
        |selectattr('entity_id','search','tbsh3_*')
        |list|count|int(-1) > 0 }}

  - name: "docker_tbsh5_containersoff"
    unique_id: docker_tbsh5_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 60
    state: >
      {{states.switch
        |selectattr('state', 'eq', 'off')
        |selectattr('entity_id','search','tbsh5_*')
        |list|count|int(-1) }}
    attributes:
      containers: >
        {{ states.switch
          |selectattr('state', 'eq', 'off')
          |selectattr('entity_id','search','tbsh5_*')
          |map(attribute='name')|join(', ') }}
      category: docker
      availability: >
        {{ states.switch
        |selectattr('state', 'eq', 'on')
        |selectattr('entity_id','search','tbsh5_*')
        |list|count|int(-1) > 0 }}

  - name: "docker_pi4srv_containersoff"
    unique_id: docker_pi4srv_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 60
    state: >
      {{states.switch
        |selectattr('state', 'eq', 'off')
        |selectattr('entity_id','search','pi4srv_*')
        |list|count|int(-1) }}
    attributes:
      containers: >
        {{ states.switch
          |selectattr('state', 'eq', 'off')
          |selectattr('entity_id','search','pi4srv_*')
          |map(attribute='name')|join(', ') }}
      category: docker
      availability: >
        {{ states.switch
        |selectattr('state', 'eq', 'on')
        |selectattr('entity_id','search','pi4srv_*')
        |list|count|int(-1) > 0 }}
