---
binary_sensor:
  - name: "[GDACS] Alert Active"
    unique_id: gdacs_alerts_active
    icon: mdi:pulse
    state: "{{ states.geo_location|selectattr('attributes.source','eq','gdacs')|list|count|int(-1) > 0 }}"
    attributes:
      category: gdacs
      last_alert: >
        {% if states.geo_location|selectattr('attributes.source','eq','gdacs')|list|count|int(-1) > 0 %}
          {{ states.geo_location|selectattr('attributes.source','eq','gdacs')
              |sort(reverse=true,attribute='attributes.from_date')
              |map(attribute='attributes.friendly_name')|first }}
        {%- else %} None Recorded
        {%- endif %}
      last_alert_desc: >
        {% if states.geo_location|selectattr('attributes.source','eq','gdacs')|list|count|int(-1) > 0 %}
          {{ states.geo_location|selectattr('attributes.source','eq','gdacs')
              |sort(reverse=true,attribute='attributes.from_date')
              |map(attribute='attributes.description')|first }}
        {%- else %} None Recorded
        {%- endif %}
      last_alert_date: >
        {% if states.geo_location|selectattr('attributes.source','eq','gdacs')|list|count|int(-1) > 0 %}
          {%- set last_date = states.geo_location|selectattr('attributes.source','eq','gdacs')
              |sort(reverse=true,attribute='attributes.from_date')
              |map(attribute='attributes.from_date')|first %}
          {{ last_date|as_timestamp(none)|timestamp_custom('%Y-%m-%d',true,none) }}
        {%- else %} None Recorded
        {%- endif %}
      last_alert_severity: >
        {% if states.geo_location|selectattr('attributes.source','eq','gdacs')|list|count|int(-1) > 0 %}
          {{ states.geo_location|selectattr('attributes.source','eq','gdacs')
              |sort(reverse=true, attribute='attributes.from_date')
              |map(attribute='attributes.alert_level')|first }}
        {%- else %} None Recorded
        {%- endif %}
    availability: >
      {{ states.geo_location|selectattr('attributes.source','eq','gdacs')|list|count|int(-1) > 0 }}
