---
sensor:
  - unique_id: hass_next_release
    state: >
      {%- set start_time = state_attr('calendar.home_assistant_devs', 'start_time') %}
      {{ (as_timestamp(start_time, default=0) + 60*60*20.5) | timestamp_local(default) }}
    attributes:
      friendly_name: >
        {%- set release = state_attr('calendar.home_assistant_devs','message') %}
        {%- if release == 'Home Assistant Core Beta Release' %}
          Beta Core Release
        {%- elif release == 'Home Assistant Core Release' %}
          Core Release
        {%- else %}
          {{ release }}
        {%- endif %}
      icon: mdi:dev-to
      device_class: timestamp
