---
sensor:
  - name: helper_dayofweek
    unique_id: helper_dayofweek
    icon: mdi:calendar-arrow-right
    state: >
      {{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}
    attributes:
      friendly_name: Day of Week

  - name: helper_daymonth
    unique_id: helper_daymonth
    icon: mdi:calendar
    state: >
      {{ ['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th','30th','31st' ][ now().day-1] }}
    attributes:
      friendly_name: Day of Month

  - name: helper_daymonthstring
    unique_id: helper_daymonthstring
    state: >
      {%- set months = ['January','February','March','April','May','June','July','August','September','October','November','December'] %}
      {%- set days = ['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th','30th','31st' ] %}
      {{ days[now().day-1] | string + ' ' + months[now().month-1]}}

  - name: helper_monthname
    unique_id: helper_monthname
    icon: mdi:calendar
    state: >
      {{ ['January','February','March','April','May','June','July','August','September','October','November','December'][now().month-1] }}
    attributes:
      friendly_name: Month Name

  - name: helper_daysremaininginmonth
    unique_id: helper_daysremaininginmonth
    icon: mdi:calendar-today
    unit_of_measurement: Days
    state: >
      {%- set this = now().replace(hour=0).replace(minute=0).replace(second=0).replace(microsecond=0) %}
      {%- set next = this.month + 1 if this.month + 1 <= 12 else 1 %}
      {%- set last = this.replace(year=this.year + 1, month=1, day=1) if now().month == 12 else this.replace(month=next, day=1) %}
      {{ (last.date() - this.date()).days - 1 }}
    attributes:
      friendly_name: Days Remaining in Month

  - name: helper_dayspassedinmonth
    unique_id: helper_dayspassedinmonth
    icon: mdi:calendar-today
    unit_of_measurement: Days
    state: >
      {%- set this = now().replace(hour=0).replace(minute=0).replace(second=0).replace(microsecond=0) %}
      {%- set next = this.month + 1 if this.month + 1 <= 12 else 1 %}
      {%- set first = this.replace(day=1) %}
      {{ (this.date() - first.date()).days }}
    attributes:
      friendly_name: Days Passed in Month

  - name: helper_daysremaininginyear
    unique_id: helper_daysremaininginyear
    icon: mdi:calendar-today
    unit_of_measurement: Days
    state: >
      {%- set this = now().replace(hour=0).replace(minute=0).replace(second=0).replace(microsecond=0) %}
      {%- set next = this.year + 1 %}
      {%- set last = this.replace(year=next, month=1, day=1) %}
      {{ (last.date() - this.date()).days }}
    attributes:
      friendly_name: Days Remaining in Year

  - name: helper_dayspassedinyear
    unique_id: helper_dayspassedinyear
    icon: mdi:calendar-today
    unit_of_measurement: Days
    state: >
      {%- set this = now().replace(hour=0).replace(minute=0).replace(second=0).replace(microsecond=0) %}
      {%- set first = this.replace(month=1, day=1) %}
      {{ (this.date() - first.date()).days }}
    attributes:
      friendly_name: Days Passed in Year

  - name: helper_timeofdayintro
    unique_id: helper_timeofdayintro
    icon: mdi:calendar
    state: >-
      {% set time = states('sensor.time') %}
      {% if time >= '05:00' and time <= '12:00' -%}
        Good morning
      {% elif time >= '12:00' and time < '17:00' -%}
        Good afternoon
      {% elif time >= '19:00' and time < '23:00' -%}
        Good evening
      {% elif time >= '23:00' -%}
        Good night
      {% elif time < '04:00' -%}
        Good night
      {% else %}
        Hi
      {% endif %}
