---
binary_sensor:
  - name: "[Presence] People Home"
    unique_id: presence_people_home
    icon: mdi:account-supervisor-circle
    device_class: presence
    state: >
      {{ is_state('binary_sensor.presence_home_occupied', 'on') }}
    attributes:
      category: presence

  - name: "[Presence] Home Occupied"
    unique_id: presence_home_occupied
    state: >
      {{ states('zone.home') | int > 0 }}
    device_class: occupancy
    attributes:
      category: presence
      is_home_full: |
        {{ states('zone.home')|int == expand(states.person)|list|count }}
      present_persons: |
        {{ expand(states.person)
          | selectattr('state', 'eq', 'home')
          | map(attribute='attributes.friendly_name')
          | list | sort }}

  - name: "[Presence] Thomas Home"
    unique_id: presence_thomas_home
    icon: "{{ iif(is_state('binary_sensor.presence_thomas_home','on'),'mdi:account-circle','mdi:account-circle-outline')}}"
    device_class: presence
    delay_off: 2
    delay_on: 2
    state: >
      {{ is_state('person.thomas_baxter','home') }}
    attributes:
      just_arrived: >
        {{ is_state('binary_sensor.presence_thomas_home','on')
            and now() - states.binary_sensor.presence_thomas_home.last_changed < timedelta(minutes=15) }}
      category: presence

  - name: "[Presence] Presence Mode Alert"
    unique_id: presence_presence_mode_alert
    device_class: problem
    delay_on: 900
    state: >
      {{ ((states('input_select.presence_mode') in ['Away','Vacation'] and is_state('binary_sensor.presence_people_home','on'))
          or ((states('input_select.presence_mode') in ['Home','Guest','Night'] and is_state('binary_sensor.presence_people_home','off'))
          or (is_state('input_select.presence_mode','Guest') and is_state('binary_sensor.presence_thomas_home','on'))))
          and is_state('input_boolean.alerts_presence','on')
      }}
    attributes:
      category: presence
