---
trigger:
  - platform: state
    entity_id: media_player.office_sonos
    attribute: media_title
sensor:
  - name: Office Sonos Recent Tracks
    unique_id: office_sonos_recent_tracks
    state: "{{ now().timestamp() | timestamp_custom() }}"
    attributes:
      last_update: >
        {{ now().timestamp() | timestamp_custom() }}
      tracks: >
        {% set current = this.attributes.get('tracks', []) %}
        {% set new = [{
            "artist": trigger.to_state.attributes.media_artist,
            "title": trigger.to_state.attributes.media_title,
            "time": now().isoformat() }]
            if is_state('media_player.office_sonos', 'playing') else [] %}
        {{ (new + current)[:10] }}
