---
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: event_template_reloaded
  - platform: state
    entity_id:
      - sensor.weather_forecasts
sensor:
  - name: Tamworth Airport Hourly Forecast Temperature Rising
    state: >
      {{ iif (state_attr('weather.east_tamworth_hourly', 'temperature') < ((state_attr('sensor.weather_forecasts', 'bom_hourly') | map(attribute='temperature') | slice(6) | first() | sum / 4)), 'Rising', 'Falling') }}
  - name: Tamworth Airport Hourly Forecast Wind Speed Increasing
    state: >
      {{ iif (state_attr('weather.east_tamworth_hourly', 'wind_speed') < ((state_attr('sensor.weather_forecasts', 'bom_hourly') | map(attribute='wind_speed') | slice(6) | first() | sum / 4)), 'Increasing', 'Decreasing') }}
  - name: Outside Hourly Forecast Wind Speed Increasing
    state: >
      {{ iif (state_attr('weather.weatherflow_forecast_brisbane_st', 'wind_speed') < ((state_attr('sensor.weather_forecasts', 'weatherflow_hourly') | map(attribute='wind_speed') | slice(6) | first() | sum / 4)), 'Increasing', 'Decreasing') }}
