---
id: notify_action_restart_zigbee2mqtt
alias: "[Notifications Action] Restart Zigbee2MQTT"
max_exceeded: silent
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: notify_action_restart_zigbee2mqtt
action:
  - service: hassio.addon_restart
    data:
      addon: 45df7312_zigbee2mqtt_edge
