---
id: notify_action_start_weatherflow2mqtt
alias: "[Notifications Action] Start Weatherflow2MQTT Docker Container"
max_exceeded: silent
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: notify_action_start_weatherflow2mqtt
action:
  - service: switch.turn_on
    target:
      entity_id: switch.tbsh5_monitordocker_weatherflow2mqtt
