---
id: notify_action_restart_gdbackup
alias: "[Notifications Action] Start Google Drive Backup"
max_exceeded: silent
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: notify_action_restart_gdbackup
action:
  - service: hassio.addon_start
    data:
      addon: cebe7a76_hassio_google_drive_backup
