---
id: notify_action_start_sungather
alias: "[Notifications Action] Start Sungather Docker Container"
max_exceeded: silent
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: notify_action_start_sungather
action:
  - service: switch.turn_on
    target:
      entity_id: switch.tbsh5_monitordocker_sungather
