---
alias: "[OpenUV] Update During Day"
id: 003780ee-c3a1-475a-b54f-8f2ef3a5c2dcß
trigger:
  - platform: time_pattern
    minutes: "/20"
condition:
  - condition: state
    entity_id: binary_sensor.connected_wan
    state: "on"
  - condition: sun # only run between sunrise and sunset
    after: sunrise
  - condition: sun
    before: sunset
action:
  service: homeassistant.update_entity
  target:
    entity_id:
      - sensor.current_uv_index
