---
alias: OpenUV - Update During Day (15min Interval)
id: 003780ee-c3a1-475a-b54f-8f2ef3a5c2dcß
trigger:
  - platform: time_pattern
    minutes: "/15"
condition:
  - condition: sun
    after: sunrise
    before: sunset
    before_offset: "+00:45:00"
  - condition: template
    value_template: >-
      {{
        state_attr('automation.openuv_update_during_day_15min_interval', 'last_triggered') == None
        or (
          now() - state_attr('automation.openuv_update_during_day_15min_interval', 'last_triggered')
        ) >= timedelta(hours = 0, minutes = 40)
      }}
action:
  service: homeassistant.update_entity
  target:
    entity_id:
      # Update both UV and protection window data:
      - binary_sensor.protection_window
      - sensor.current_uv_index
