---
resource: https://timeapi.io/api/TimeZone/zone?timeZone=Europe/London
sensor:
  name: dst_dates_uk
  unique_id: dst_dates_uk
  value_template: "{{ value_json.isDayLightSavingActive }}"
  json_attributes_path: "$.dstInterval"
  json_attributes:
    - dstStart
    - dstEnd
scan_interval: 21600
