---
alias: System - Home Assistant Stopped
id: d1ad0063-ee92-4584-8b72-0084511e4609
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.tbsmarthome
    data_template:
      message: "Home Assistant Stopped"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*Home Assistant Stopped*"
          - type: section
            text:
              type: mrkdwn
              text: Home Assistant Stopped
