---
alias: System - Home Assistant Started
id: 153774e8-d77a-4cf1-b859-11d7095faa5d
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.tbsmarthome
    data_template:
      message: "Home Assistant Started"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*Home Assistant Started*"
          - type: section
            text:
              type: mrkdwn
              text: Home Assistant Started
