---
alias: AutoGroup - Media Players
id: autogroup_media_players
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/2"
action:
  - service: group.set
    data_template:
      object_id: media_players
      entities: >-
        {%-
          for state in states.media_player
        %}
        {{ state.entity_id }}{%- if not loop.last -%}, {%- endif -%}
        {%- endfor %}
