---
alias: "[HA] Update Groups Automatically"
mode: restart
trigger:
  - platform: homeassistant
    id: startup
    event: start

  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: reload

  - platform: time_pattern
    hours: "/2"

action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 60

  - service: group.set
    data_template:
      object_id: battery_devices
      entities: >-
        {%-
          for state in states.sensor
            if is_state_attr(state.entity_id, 'device_class', 'battery') and
            (state.entity_id.endswith("_battery") or state.entity_id.endswith("_power"))
        %}
        {{ state.entity_id }}{%- if not loop.last -%}, {%- endif -%}
        {%- endfor %}

  - service: group.set
    data_template:
      object_id: media_players
      entities: >-
        {%- for state in states.media_player %}
        {{ state.entity_id }}{%- if not loop.last -%}, {%- endif -%}
        {%- endfor %}

  - service: group.set
    data:
      object_id: lights
      entities: >
        {{ states.light
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: alert_controls
      entities: >
        {{ states
            |selectattr('entity_id','search','input_boolean.alerts_*')
            |map(attribute='entity_id')|list|sort }}
