---
alias: "[HA] Count Triggered Automations"
id: ha_count_triggered_automations
mode: parallel
max: 25
max_exceeded: silent
trigger:
  - platform: event
    event_type: automation_triggered
condition:
  - condition: template
    value_template: "{{ not 'ha_count_triggered_automations' in (trigger.event.data.name|string) }}"
  - condition: template
    value_template: "{{ not 'system_esphome_ble_advert' in (trigger.event.data.name|string) }}"
action:
  - service: counter.increment
    entity_id: counter.automation_trigger_counter