---
resource: https://api.github.com/repos/home-assistant/core/releases/latest
sensor:
  name: hass_release_notes
  unique_id: hass_release_notes
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
scan_interval: 21600
