---
resource: !secret lastfm_monthlytrackchart_url
sensor:
  name: lastfm_user_monthlytrackchart
  value_template: >
    {{ value_json.toptracks.track[0].artist.name}} - {{ value_json.toptracks.track[0].name }}
  json_attributes_path: $.toptracks
  json_attributes:
    - track
scan_interval: 600
