---
resource: http://192.168.1.132:8084/ajax/aircraft
sensor:
  name: flighttracker_plane_finder_aircraft
  unique_id: flighttracker_plane_finder_aircraft
  value_template: "ADS-B"
  json_attributes_path: $.aircraft
  # json_attributes:
  #   - callsign
  #   - reg
  #   - flightno
  #   - route
  #   - type
scan_interval: 10
