---
sensor:
  - platform: average
    name: today_temp_bom
    entities:
      - sensor.tamworth_airport_temp
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: template
    sensors:
      bom_beaufort:
        value_template: >
          {%- if states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 118 -%}
          12
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 103 -%}
          11
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 89 -%}
          10
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 75 -%}
          9
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 62 -%}
          8
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 50 -%}
          7
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 39 -%}
          6
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 29 -%}
          5
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 20 -%}
          4
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 12 -%}
          3
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 6 -%}
          2
          {%- elif states('sensor.tamworth_airport_wind_speed_kilometre') | float(default=0)  >= 2 -%}
          1
          {%- else -%}
          0
          {%- endif -%}
      bom_heatindex:
        unit_of_measurement: °C
        device_class: temperature
        value_template: >
          {%- if states('sensor.tamworth_airport_temp') | float(default=0) > 27 and states('sensor.tamworth_airport_humidity') | float(default=0) > 40 -%}
          {% set T = states('sensor.tamworth_airport_temp') | float(default=0) %}
          {% set R = states('sensor.tamworth_airport_humidity') | float(default=0) %}
          {% set c1 = -8.78469475556 %}
          {% set c2 = 1.61139411 %}
          {% set c3 = 2.33854883889 %}
          {% set c4 = -0.14611605 %}
          {% set c5 = -0.012308094 %}
          {% set c6 = -0.0164248277778 %}
          {% set c7 = 0.002211732 %}
          {% set c8 = 0.00072546 %}
          {% set c9 = -0.000003582 %}
          {% set HI = c1 + (c2 * T ) + (c3 * R) + ( c4 * T * R ) + ( c5 * T**2 ) + ( c6 * R**2 ) + ( c7 * T**2 * R ) + ( c8 * T * R**2 ) + ( c9 * T**2 * R**2 ) %}
          {{ HI | round }}
          {%- else -%}
          0
          {%- endif -%}
      bom_heatindexrating:
        value_template: >
          {%- if states('sensor.bom_heatindex') == 'n/a' -%}
          Out of range
          {%- elif states('sensor.bom_heatindex') | float(default=0)  >= 54 -%}
          Extreme danger: heat stroke imminent
          {%- elif states('sensor.bom_heatindex') | float(default=0)  >= 41 -%}
          Danger: cramps, exhaustion heat stroke probable
          {%- elif states('sensor.bom_heatindex') | float(default=0)  >= 32 -%}
          Extreme caution: cramps and exhaustion possible
          {%- elif states('sensor.bom_heatindex') | float(default=0)  >= 26 -%}
          Caution: fatigue possible
          {%- else -%}
          Normal
          {%- endif -%}
