---
homeassistant:
  customize:
    sensor.date:
      friendly_name: Current Date
    sensor.time:
      friendly_name: Current Time - Home
    sensor.time_utc:
      friendly_name: Current Time - UTC
    sensor.time_london:
      friendly_name: Current Time - UK (London)
    sensor.time_new_york:
      friendly_name: Current Time - US (New York)

binary_sensor:
  - platform: tod
    name: Early Morning
    after: sunrise
    after_offset: "-02:00"
    before: "07:00"

  - platform: tod
    name: Late Morning
    after: "10:00"
    before: "12:00"

  - platform: tod
    name: Night
    after: sunset
    before: sunrise

  - platform: tod
    name: Day
    after: sunrise
    before: sunset

  - platform: tod
    name: Work
    after: "07:00"
    before: "17:00"
