---
sensor:
  - platform: template
    sensors:
      # ----- Count All Entities
      count_all_entities:
        unique_id: count_all_entities
        friendly_name: "All Entities"
        icon_template: mdi:code-tags
        unit_of_measurement: Count
        value_template: >
          {{ states | count | int(default=0) }}

      count_all_domains:
        unique_id: count_all_domains
        friendly_name: "Domains in Use"
        icon_template: mdi:domain
        unit_of_measurement: Count
        value_template: >
          {%- for d in states | groupby('domain') %}
          {%- if loop.first %}
          {{loop.length | int(default=0)}}
          {%- endif %}
          {%- endfor %}

      # ----- Count Alarm Control Panels
      count_alarm_control_panels:
        friendly_name: "Alarm Control Panels"
        icon_template: mdi:alarm-panel
        unit_of_measurement: Count
        value_template: >
          {{ states.alarm_control_panel | list | length | int(default=0) }}

      # ----- Count Automations
      count_automations:
        friendly_name: "Automations"
        icon_template: mdi:robot
        unit_of_measurement: Count
        value_template: >
          {{ states.automation | list | length | int(default=0) }}

      # ----- Count Binary Sensors
      count_binary_sensors:
        friendly_name: "Binary Sensors"
        icon_template: mdi:checkbox-multiple-marked-circle
        unit_of_measurement: Count
        value_template: >
          {{ states.binary_sensor | list | length | int(default=0) }}

      # ----- Count Buttons
      count_buttons:
        friendly_name: "Buttons"
        icon_template: mdi:gesture-tap-button
        unit_of_measurement: Count
        value_template: >
          {{ states.button | list | length | int(default=0) }}

      # ----- Count Calendars
      count_calendars:
        friendly_name: "Calendars"
        icon_template: mdi:calendar
        unit_of_measurement: Count
        value_template: >
          {{ states.calendar | list | length | int(default=0) }}

      # ----- Count Cameras
      count_cameras:
        friendly_name: "Cameras"
        icon_template: mdi:cctv
        unit_of_measurement: Count
        value_template: >
          {{ states.camera | list | length | int(default=0) }}

      # ----- Count Climate
      count_climate:
        friendly_name: "Climate"
        icon_template: mdi:home-thermometer
        unit_of_measurement: Count
        value_template: >
          {{ states.climate | list | length | int(default=0) }}

      # ----- Count Counters
      count_counters:
        friendly_name: "Counters"
        icon_template: mdi:counter
        unit_of_measurement: Count
        value_template: >
          {{ states.counter | list | length | int(default=0) }}

      # ----- Count Device Trackers
      count_device_trackers:
        friendly_name: "Devices"
        icon_template: mdi:cellphone-link
        unit_of_measurement: Count
        value_template: >
          {{ states.device_tracker | list | length | int(default=0) }}

      # ----- Count Fans
      count_fans:
        friendly_name: "Fans"
        icon_template: mdi:fan
        unit_of_measurement: Count
        value_template: >
          {{ states.fan | list | length | int(default=0) }}

      # ----- Count Geo Locations
      count_geolocation:
        friendly_name: "Geo Locations"
        icon_template: mdi:map-plus
        unit_of_measurement: Count
        value_template: >
          {{ states.geo_location | list | length | int(default=0) }}

      # ----- Count Groups
      count_groups:
        friendly_name: "Groups"
        icon_template: mdi:group
        unit_of_measurement: Count
        value_template: >
          {{ states.group | list | length | int(default=0) }}

      # ----- Count Input Booleans
      count_input_booleans:
        friendly_name: "Input Booleans"
        icon_template: mdi:toggle-switch
        unit_of_measurement: Count
        value_template: >
          {{ states.input_boolean | list | length | int(default=0) }}

      # ----- Count Input Date Times
      count_input_datetimes:
        friendly_name: "Input Date Times"
        icon_template: mdi:calendar
        unit_of_measurement: Count
        value_template: >
          {{ states.input_datetime | list | length | int(default=0) }}

      # ----- Count Input Numbers
      count_input_numbers:
        friendly_name: "Input Numbers"
        icon_template: mdi:numeric
        unit_of_measurement: Count
        value_template: >
          {{ states.input_number | list | length | int(default=0) }}

      # ----- Count Input Selects
      count_input_selects:
        friendly_name: "Input Selects"
        icon_template: mdi:format-align-justify
        unit_of_measurement: Count
        value_template: >
          {{ states.input_select | list | length | int(default=0) }}

      # ----- Count Input Texts
      count_input_texts:
        friendly_name: "Input Texts"
        icon_template: mdi:alphabetical
        value_template: >
          {{ states.input_text | list | length | int(default=0) }}

      # ----- Count Lights
      count_lights:
        friendly_name: "Lights"
        icon_template: mdi:lightbulb-on
        unit_of_measurement: Count
        value_template: >
          {{ states.light | list | length | int(default=0) }}

      # ----- Count Media Players
      count_mediaplayers:
        friendly_name: "Media Players"
        icon_template: mdi:cast-connected
        unit_of_measurement: Count
        value_template: >
          {{ states.media_player | list | length | int(default=0) }}

      # ----- Count Numbers
      count_numbers:
        friendly_name: "Numbers"
        icon_template: mdi:numeric
        unit_of_measurement: Count
        value_template: >
          {{ states.number | list | length | int(default=0) }}

      # ----- Count Persistent Notifications
      count_persistent_notifications:
        friendly_name: "Persistent Notifications"
        unit_of_measurement: Count
        icon_template: mdi:bell
        value_template: >
          {{ states.persistent_notification | list | length | int(default=0) }}

      # ----- Count Persons
      count_persons:
        friendly_name: "Persons"
        icon_template: mdi:account-multiple
        unit_of_measurement: Count
        value_template: >
          {{ states.person | list | length | int(default=0) }}

      # ----- Count Remote
      count_remotes:
        friendly_name: "Remotes"
        icon_template: mdi:remote
        unit_of_measurement: Count
        value_template: >
          {{ states.remote | list | length | int(default=0) }}

      # ----- Count Scripts
      count_scripts:
        friendly_name: "Scripts"
        icon_template: mdi:script-text-outline
        unit_of_measurement: Count
        value_template: >
          {{ states.script | list | length | int(default=0) }}

      # ----- Count Selects
      count_selects:
        friendly_name: "Selects"
        icon_template: mdi:select-all
        unit_of_measurement: Count
        value_template: >
          {{ states.select | list | length | int(default=0) }}

      # ----- Count Sensors
      count_sensors:
        friendly_name: "Sensors"
        icon_template: mdi:pulse
        unit_of_measurement: Count
        value_template: >
          {{ states.sensor | list | length | int(default=0) }}

      # ----- Count Suns
      count_suns:
        friendly_name: "Suns"
        icon_template: mdi:weather-sunny-alert
        unit_of_measurement: Count
        value_template: >
          {{ states.sun | list | length | int(default=0) }}

      # ----- Count Switches
      count_switches:
        friendly_name: "Switches"
        icon_template: mdi:power-socket-au
        unit_of_measurement: Count
        value_template: >
          {{ states.switch | list | length | int(default=0) }}

      # ----- Count Weather
      count_weathers:
        friendly_name: "Weathers"
        icon_template: mdi:weather-cloudy-alert
        unit_of_measurement: Count
        value_template: >
          {{ states.weather | list | length | int(default=0) }}

      # ----- Count Zones
      count_zones:
        friendly_name: "Zones"
        icon_template: mdi:map-marker-radius
        unit_of_measurement: Count
        value_template: >
          {{ states.zone | list | length | int(default=0) }}
