---
# binary_sensor:
#   - platform: ping
#     host: 1.1.1.1
#     name: "[Connected] WAN"
#     count: 5
#     scan_interval: 60

sensor:
  - platform: rest
    name: nbn_location_home
    resource: https://places.nbnco.net.au/places/v2/details/LOC000018433654
    headers:
      Referer: https://www.nbnco.com.au/
    value_template: "{{ value_json.addressDetail.altReasonCode }}"
    scan_interval: 7200 # update the value every 2 hours
    json_attributes:
      - servingArea
      - addressDetail

  - platform: rest
    name: nbn_location_dadwork
    resource: https://places.nbnco.net.au/places/v2/details/LOC000107178217
    headers:
      Referer: https://www.nbnco.com.au/
    value_template: "{{ value_json.addressDetail.altReasonCode }}"
    scan_interval: 7200 # update the value every 2 hours
    json_attributes:
      - servingArea
      - addressDetail

  - platform: template
    sensors:
      nbn_status_home:
        friendly_name: "NBN Status (Home)"
        unique_id: nbn_status_home
        value_template: >
          {%- set tech_status = state_attr('sensor.nbn_location_home', 'addressDetail')['techChangeStatus'] %}
          {%- set status_map = {
            'Not Planned': 'No FTTP upgrade',
            'Planned': 'FTTP Planned',
            'In Design': 'FTTP Upgrade in Design',
            'Committed': 'FTTP Upgrade Committed',
            'Build Finalised': 'FTTP Upgrade Build Finalized',
            'Eligible To Order': 'FTTP Upgrade Eligible to Order',
            'MDU Complex Eligible To Apply': 'MDU Complex Eligible to Apply',
            'New Tech Connected': 'New Technology Connected',
            'Previous Tech Disconnected': 'Previous Technology Disconnected'
          } %}
          {{ status_map[tech_status] if tech_status in status_map else tech_status }}
          
      nbn_status_work:
        friendly_name: "NBN Status (Work)"
        unique_id: nbn_status_work
        value_template: >
          {%- set tech_status = state_attr('sensor.nbn_location_dadwork', 'addressDetail')['techChangeStatus'] %}
          {%- set status_map = {
            'Not Planned': 'No FTTP upgrade',
            'Planned': 'FTTP Planned',
            'In Design': 'FTTP Upgrade in Design',
            'Committed': 'FTTP Upgrade Committed',
            'Build Finalised': 'FTTP Upgrade Build Finalized',
            'Eligible To Order': 'FTTP Upgrade Eligible to Order',
            'MDU Complex Eligible To Apply': 'MDU Complex Eligible to Apply',
            'New Tech Connected': 'New Technology Connected',
            'Previous Tech Disconnected': 'Previous Technology Disconnected'
          } %}
          {{ status_map[tech_status] if tech_status in status_map else tech_status }}
