---
binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: Online
    count: 1
    scan_interval: 300

sensor:
  - platform: rest
    name: nbn_location_home
    resource: https://places.nbnco.net.au/places/v2/details/LOC000018433654
    headers:
      Referer: https://www.nbnco.com.au/
    value_template: "{{ value_json.addressDetail.altReasonCode }}"
    scan_interval: 7200 # update the value every 2 hours
    json_attributes:
      - servingArea
      - addressDetail

  - platform: rest
    name: nbn_location_dadwork
    resource: https://places.nbnco.net.au/places/v2/details/LOC000107178217
    headers:
      Referer: https://www.nbnco.com.au/
    value_template: "{{ value_json.addressDetail.altReasonCode }}"
    scan_interval: 7200 # update the value every 2 hours
    json_attributes:
      - servingArea
      - addressDetail

  - platform: template
    sensors:
      nbn_status_home:
        friendly_name: "NBN Status"
        value_template: >-
          {% set alt_reason_code = states('sensor.nbn_location_home') %}
          {% if alt_reason_code == 'NULL_NA' %}
            No FTTP upgrade
          {% elif alt_reason_code == 'FTTP_NA' %}
            FTTP Upgrade coming soon
          {% elif alt_reason_code == 'FTTP_SA' %}
            FTTP Upgrade available
          {% else %}
            {% if alt_reason_code %}
              {{ alt_reason_code }} was returned
            {% else %}
              Error
            {% endif %}
          {% endif %}
