---
sensor:
  - platform: average
    name: lightning_counter_lasthour
    unique_id: lightning_counter_lasthour
    entities:
      - sensor.blitzortung_lightning_counter
    duration:
      hours: 1
  - platform: average
    name: lightning_distance_lasthour
    unique_id: lightning_distance_lasthour
    entities:
      - sensor.blitzortung_lightning_distance
    duration:
      hours: 1
  - platform: template
    sensors:
      lightning_countbolts_lasthour:
        value_template: >
          {{ states.geo_location |selectattr('attributes.source','eq','blitzortung') | list | length  | int(default=0) }}
        unit_of_measurement: "↯"
