---
homeassistant:
  customize:
    sensor.xiaomibedroom_min_temp:
      friendly_name: "Bedroom Min Temp (Last 24hrs)"
      icon: mdi:thermometer-chevron-down
      unit_of_measurement: "°C"
    sensor.xiaomibedroom_max_temp:
      friendly_name: "Bedroom MaxTemp (Last 24hrs)"
      icon: mdi:thermometer-chevron-up
      unit_of_measurement: "°C"
    sensor.xiaomibedroom_change_temp:
      friendly_name: "Bedroom Temp Change (Last 24hrs)"
      icon: mdi:thermometer-lines
      unit_of_measurement: "°C"
    sensor.xiaomioffice_min_temp:
      friendly_name: "Office Min Temp (Last 24hrs)"
      icon: mdi:thermometer-chevron-down
      unit_of_measurement: "°C"
    sensor.xiaomioffice_max_temp:
      friendly_name: "Office MaxTemp (Last 24hrs)"
      icon: mdi:thermometer-chevron-up
      unit_of_measurement: "°C"

    sensor.xiaomioffice_change_temp:
      friendly_name: "Office Temp Change (Last 24hrs)"
      icon: mdi:thermometer-lines
      unit_of_measurement: "°C"

sensor:
  - platform: statistics
    name: xiaomibedroom_min_temp
    state_characteristic: value_min
    sampling_size: 150
    entity_id: sensor.z2m_bedroom_climate_temperature
    max_age:
      hours: 24

  - platform: statistics
    name: xiaomibedroom_max_temp
    state_characteristic: value_max
    sampling_size: 150
    entity_id: sensor.z2m_bedroom_climate_temperature
    max_age:
      hours: 24

  - platform: statistics
    name: xiaomibedroom_change_temp
    state_characteristic: change
    sampling_size: 150
    entity_id: sensor.z2m_bedroom_climate_temperature
    max_age:
      hours: 24

  - platform: statistics
    name: xiaomioffice_min_temp
    state_characteristic: value_min
    sampling_size: 150
    entity_id: sensor.z2m_office_airquality_temperature_filtered
    max_age:
      hours: 24

  - platform: statistics
    name: xiaomioffice_max_temp
    state_characteristic: value_max
    sampling_size: 150
    entity_id: sensor.z2m_office_airquality_temperature_filtered
    max_age:
      hours: 24

  - platform: statistics
    name: xiaomioffice_change_temp
    state_characteristic: change
    sampling_size: 150
    entity_id: sensor.z2m_office_airquality_temperature_filtered
    max_age:
      hours: 24
