---
homeassistant:
  customize_glob:
    package.node_anchors:
      customize: &customize
        package: "fuel"
        icon: mdi:fuel

    "sensor.fuelcheck_*":
      <<: *customize

sensor:
  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types:
      - U91
      - E10
      - P98
      - P95
    station_id: 16921
    # Ampol White Stret

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types:
      - U91
      - E10
      - P98
      - P95
    station_id: 573
    # EG Ampol Bridge St

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types:
      - U91
      - E10
      - P98
      - P95
    station_id: 18350
    # Ampol Gunnedah Rd

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types:
      - U91
      - E10
      - P98
      - P95
    station_id: 1543
    # Ampol Goonoo Goonoo Road

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types:
      - U91
      - E10
      - P98
      - P95
    station_id: 16919
    # Ampol Moonbi

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types:
      - U91
      - E10
      - P98
      - P95
    station_id: 18593
    # Ampol Barraba
