---
sensor:
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.espn.com.au/espn/rss/news
    inclusions:
      - image
      - link
      - published
      - title
    name: ESPN Australia
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: http://feeds.bbci.co.uk/news/rss.xml
    inclusions:
      - image
      - link
      - published
      - title
    name: BBC
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: http://rss.cnn.com/rss/cnn_latest.rss
    inclusions:
      - image
      - link
      - published
      - title
    name: CNN
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: http://www.news.com.au/feed
    inclusions:
      - image
      - link
      - published
      - title
    name: news.com.au
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: http://feeds.skynews.com/feeds/rss/home.xml
    inclusions:
      - image
      - link
      - published
      - title
    name: Sky News UK
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.smh.com.au/rss/feed.xml
    inclusions:
      - image
      - link
      - published
      - title
    name: Sydney Morning Herald
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.smh.com.au/rss/sport.xml
    inclusions:
      - image
      - link
      - published
      - title
    name: Sydney Morning Herald Sport
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.foxsports.com.au/content-feeds/breaking-news/
    inclusions:
      - image
      - link
      - published
      - title
    name: Fox Sports
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.northerndailyleader.com.au/rss.xml
    inclusions:
      - image
      - link
      - published
      - title
    name: Northern Daily Leader
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.theguardian.com/au/rss
    inclusions:
      - image
      - link
      - published
      - title
    name: The Guardian (AU)
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.theguardian.com/uk/rss
    inclusions:
      - image
      - link
      - published
      - title
    name: The Guardian (UK)
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.skysports.com/rss/12040
    inclusions:
      - image
      - link
      - published
      - title
    name: Sky Sports (UK)
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.newsnationnow.com/feed/
    inclusions:
      - image
      - link
      - published
      - title
    name: NewsNation
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
    inclusions:
      - image
      - link
      - published
      - title
    name: New York Times
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.itnews.com.au/RSS/rss.ashx
    inclusions:
      - image
      - link
      - published
      - title
    name: iTNews
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.nasa.gov/news-release/feed/
    inclusions:
      - image
      - link
      - published
      - title
    name: NASA
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.speedcafe.com/feed/
    inclusions:
      - image
      - link
      - published
      - title
    name: Speedcafe
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10
  - date_format: "%a, %d %b %Y %H:%M:%S %Z"
    entity_namespace: rssfeed
    feed_url: https://www.v8sleuth.com.au/feed/
    inclusions:
      - image
      - link
      - published
      - title
    name: V8 Sleuth
    platform: feedparser
    scan_interval:
      minutes: 15
    show_topn: 10