---
homeassistant:
  customize:
    sensor.rssfeed_bbc:
      icon: si:bbc
    sensor.rssfeed_cnn:
      icon: si:cnn
    sensor.rssfeed_news_com_au:
      icon: mdi:newspaper
    sensor.rssfeed_sky_news_uk:
      icon: si:sky
    sensor.rssfeed_sydney_morning_herald:
      icon: mdi:newspaper
    sensor.rssfeed_fox_sports:
      icon: si:foxtel
    sensor.rssfeed_northern_daily_leader:
      icon: mdi:newspaper
    sensor.rssfeed_the_guardian_au:
      icon: mdi:newspaper
    sensor.rssfeed_the_guardian_uk:
      icon: mdi:newspaper
    sensor.rssfeed_sky_sports_uk:
      icon: si:sky

sensor:
  - platform: feedparser
    name: ESPN Australia
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.espn.com.au/espn/rss/news
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: BBC
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: http://feeds.bbci.co.uk/news/rss.xml
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: CNN
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: http://rss.cnn.com/rss/edition.rss
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: news.com.au
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: http://www.news.com.au/feed
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: Sky News UK
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: http://feeds.skynews.com/feeds/rss/home.xml
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: Sydney Morning Herald
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.smh.com.au/rss/feed.xml
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: Fox Sports
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.foxsports.com.au/content-feeds/breaking-news/
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: Northern Daily Leader
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.northerndailyleader.com.au/rss.xml
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: The Guardian (AU)
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.theguardian.com/au/rss
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: The Guardian (UK)
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.theguardian.com/uk/rss
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
  - platform: feedparser
    name: Sky Sports (UK)
    entity_namespace: rssfeed
    date_format: "%a, %d %b %Y %H:%M:%S %Z"
    scan_interval:
      hours: 1
    feed_url: https://www.skysports.com/rss/12040
    show_topn: 10
    inclusions:
      - title
      - image
      - published
      - link
