---
homeassistant:
  customize:
    sensor.tbsh1_package_updates:
      icon: mdi:upload-network-outline
    sensor.tbsh1_security_updates:
      icon: mdi:security-network

command_line:
  - sensor:
      unique_id: tbsh1_package_updates
      name: TBSH1 Package Updates
      unit_of_measurement: "Updates"
      scan_interval: 300
      command_timeout: 30
      command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' tbsmarthome@192.168.1.91 -T /usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1

  - sensor:
      unique_id: tbsh1_security_updates
      name: TBSH1 Security Updates
      unit_of_measurement: "Updates"
      scan_interval: 300
      command_timeout: 30
      command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' tbsmarthome@192.168.1.91 -T /usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 2
