---
binary_sensor:
  - monitored_conditions:
      - elevation:
          above: 25
          name: Sun Above 25
      - elevation
    platform: sun2

sensor:
  - monitored_conditions:
      - astronomical_dawn
      - astronomical_daylight
      - astronomical_dusk
      - astronomical_night
      - civil_daylight
      - civil_night
      - dawn
      - daylight
      - deconz_daylight
      - dusk
      - elevation
      - max_elevation
      - nautical_dawn
      - nautical_daylight
      - nautical_dusk
      - nautical_night
      - night
      - solar_midnight
      - solar_noon
      - sun_phase
      - sunrise
      - sunset
    platform: sun2
