---
sensor:
  - platform: template
    sensors:
      sun_state_day:
        friendly_name: Sun State
        value_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            Day
          {% else %}
            Night
          {% endif %}
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}

      period_of_day:
        friendly_name: "period of the day"
        value_template: >-
          {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
            dusk
          {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
            dawn
          {% elif (states.sun.sun.attributes.elevation) < -4 %}
            night
          {% else %}
            day
          {% endif %}
        icon_template: >-
          {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
            mdi:weather-sunset-down
          {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
            mdi:weather-sunset-up
          {% elif (states.sun.sun.attributes.elevation) < -4 %}
            mdi:weather-night
          {% else %}
            mdi:weather-sunny
          {% endif %}

      sun_nextdawn:
        friendly_name: Next Dawn
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-up

      sun_nextdusk:
        friendly_name: Next Dusk
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-down

      sun_nextmidnight:
        friendly_name: Next Midnight
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_midnight) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-night

      sun_nextnoon:
        friendly_name: Next Noon
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_noon) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunny

      sun_nextrising:
        friendly_name: Next Rising
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-up

      sun_nextsetting:
        friendly_name: Next Setting
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-down

      sun_solarangle:
        friendly_name: "Sun Angle"
        unit_of_measurement: "°"
        value_template: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
        icon_template: mdi:weather-sunny

      sun_angle:
        friendly_name: "Elevation"
        unit_of_measurement: "°"
        icon_template: "mdi:axis-y-rotate-clockwise"
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"

      sun_azimuth:
        friendly_name: "Azimuth"
        unit_of_measurement: "°"
        icon_template: "mdi:axis-z-rotate-clockwise"
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"

      sun_state:
        friendly_name: Sun
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}
        value_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            sets at {% set timestamp = as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M') %} {{ timestamp.lstrip('0') }}
          {% else %}
            rises at {% set timestamp = as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M') %} {{ timestamp.lstrip('0') }}
          {% endif %}

      sun_state_friendly:
        friendly_name: Sun
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}
        value_template: >-
          {% set current = as_timestamp(strptime(states('sensor.date_time'), '%Y-%m-%d, %H:%M')) %}
          {% set dusk = as_timestamp(state_attr('sun.sun', 'next_dusk')) %}
          {% if current <= dusk %}
            {% set setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% if current >= setting %}
              is setting
            {% elif (setting - current) <= 60*30 %}
              will set in a few minutes
            {% else %}
              {% set hour = setting|timestamp_custom('%H') | int %}
              {% set minute = setting|timestamp_custom('%M') | int %}
              {% set minute_friendly = '' %}
              {% set half = false %}
              {% if minute >= 10 and minute <= 20 %}
                {% set minute_friendly = 'a quarter past ' %}
              {% elif minute > 20 and minute < 40 %}
                {% set half = true %}
              {% elif minute >= 40 and minute <= 50 %}
                {% set minute_friendly = 'a quarter to ' %}
                {% set hour = hour + 1 %}
              {% elif minute > 50 %}
                {% set hour = hour + 1 %}
              {% endif %}
              {% if hour >= 24 %}
                {% set hour = hour - 24 %}
              {% endif %}
              {% if hour == 0 %}
                {% set hour_friendly = 'midnight' %}
              {% elif hour == 12 %}
                {% set hour_friendly = 'noon' %}
              {% elif hour > 12 %}
                {% set hour_friendly = hour - 12 %}
              {% else %}
                {% set hour_friendly = hour %}
              {% endif %}
              {% if half %}
                will set at around {{ hour_friendly }} and a half
              {% else %}
                will set at around {{ minute_friendly }}{{ hour_friendly }}
              {% endif %}
            {% endif %}
          {% else %}
            {% set dawn = as_timestamp(state_attr('sun.sun', 'next_dawn')) %}
            {% set rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set diff = ((rising - current) / 60 / 60) %}
            {% set hour = diff | int %}
            {% set minute = (diff - hour) | round(2) %}
            {% if hour %}
              {% if minute > 0.66 %}
                {% set hour = hour + 1 %}
              {% elif minute > 0.33 %}
                {% set minute_friendly = ' and a half' %}
              {% endif %}
              will rise in about {{hour}}{{ minute_friendly }} hour{% if hour > 0 %}s{% endif %}
            {% elif (rising - dawn) < 0%}
              is rising
            {% else %}
              will rise in a few minutes
            {% endif %}
          {% endif %}
      daylight_remaining_min:
        friendly_name: Daylight remaining minutes
        value_template: >
          {{((as_timestamp(state_attr('sun.sun','next_setting')) - now().timestamp())/60)|int}}
        unit_of_measurement: min
      daylight_remaining_hm:
        friendly_name: "Daylight remaining hh:mm"
        value_template: >
          {{(as_timestamp(state_attr('sun.sun','next_setting')) - now().timestamp())
             |timestamp_custom('%H:%M',false)}}
      nextsunrise:
        friendly_name: "Next Sunrise"
        value_template: >
          {{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        friendly_name: "Next Sunset"
        value_template: >
          {{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
      sunrisetoday:
        friendly_name: "Sunrise"
        value_template: >
          {{ as_timestamp(states('sensor.tbsmarthome_sun_rising')) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      sunsettoday:
        friendly_name: "Sunset"
        value_template: >
          {{ as_timestamp(states('sensor.tbsmarthome_sun_setting')) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
      daylightyesterday:
        friendly_name: "Day Length Yesterday"
        value_template: >
          {{ state_attr('sensor.tbsmarthome_sun_daylight', 'yesterday_hms') }}
        icon_template: mdi:weather-sunny
      daylighttoday:
        friendly_name: "Day Length Today"
        value_template: >
          {{ state_attr('sensor.tbsmarthome_sun_daylight', 'today_hms') }}
        icon_template: mdi:weather-sunny
      daylighttomorrow:
        friendly_name: "Day Length Tomorrow"
        value_template: >
          {{ state_attr('sensor.tbsmarthome_sun_daylight', 'tomorrow_hms') }}
        icon_template: mdi:weather-sunny
      daylengthchange:
        friendly_name: "Change in Day Length"
        unit_of_measurement: "seconds"
        value_template: >
          {{ ((state_attr('sensor.tbsmarthome_sun_daylight', 'today') - state_attr('sensor.tbsmarthome_sun_daylight', 'yesterday')) * 3600) | round(0) }}
        icon_template: mdi:weather-sunny
      sun_daylightpct_remain:
        friendly_name: Daylight Percent Remaining
        value_template: >
          {%- set total = state_attr('sensor.tbsmarthome_sun_daylight', 'today') %}
          {%- set used = (now() -  state_attr('sensor.tbsmarthome_sun_rising', 'today')).total_seconds() / 3600 %}
          {{  100 * ((total - used)/total ) | round(2, 0) }}
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}
        unit_of_measurement: "%"
