---
sensor:
  - league_id: XXX
    league_path: aus.1
    name: teamtracker_sydneyfc
    platform: teamtracker
    sport_path: soccer
    team_id: SYD

  - league_id: XXX
    league_path: 8326
    name: teamtracker_nswwaratahs
    platform: teamtracker
    sport_path: rugby
    team_id: WARAT

  - league_id: XXX
    league_path: 8044
    name: teamtracker_sydneysixers
    platform: teamtracker
    sport_path: cricket
    team_id: SS

  - league_id: XXX
    league_path: 8043
    name: teamtracker_cricketnswss
    platform: teamtracker
    sport_path: cricket
    team_id: NSW

  - league_id: XXX
    league_path: afl
    name: teamtracker_sydneyswans
    platform: teamtracker
    sport_path: australian-football
    team_id: SYD

  - league_id: XXX
    league_path: 3
    name: teamtracker_newcastleknights
    platform: teamtracker
    sport_path: rugby-league
    team_id: KNI
