---
sensor:
  - platform: teamtracker
    league_id: XXX
    sport_path: soccer
    league_path: aus.1
    team_id: SYD
    name: teamtracker_sydneyfc
  - platform: teamtracker
    league_id: XXX
    sport_path: rugby
    league_path: 8326
    team_id: WARAT
    name: teamtracker_nswwaratahs
  - platform: teamtracker
    league_id: XXX
    sport_path: cricket
    league_path: 8044
    team_id: SS
    name: teamtracker_sydneysixers
  - platform: teamtracker
    league_id: XXX
    sport_path: australian-football
    league_path: afl
    team_id: SYD
    name: teamtracker_sydneyswans
