---
sensor:
  - name: current_weather_hourly_next_precipitation_start
    device_class: timestamp
    state: >
      {{ (state_attr('weather.tempest_hourly', 'forecast')
        | selectattr('condition', 'in', ['rainy', 'lightning-rainy'])
        | list | first | default).datetime | default(none)
      }}

  - name: current_weather_hourly_next_precipitation_end
    device_class: timestamp
    state: >
      {{ (state_attr('weather.tempest_hourly', 'forecast')
        | rejectattr('condition', 'in', ['rainy', 'lightning-rainy'])
        | selectattr('datetime', '>', states('sensor.current_weather_hourly_next_precipitation_start'))
        | list | first | default).datetime | default(none)
      }}

  - name: current_weather_summary_now
    state: ""
    attributes:
      content: >
        Currently {{ states('sensor.tempest_st_00056115_temperature') | round(0) | string + '째' }}
        feels like  {{ states('sensor.tempest_st_00056115_feels_like_temperature') | round(0) | string + '째' }}
        {{ states('weather.tempest_hourly') }} and {{states('sensor.tempest_st_00056115_temperature_level') | lower }}.

  - name: current_weather_summary_today
    state: ""
    attributes:
      content: >
        {{ state_attr('weather.tempest_daily', 'forecast')[0].temperature  | string + '째' -}}
        / {{- state_attr('weather.tempest_daily', 'forecast')[0].templow  | string + '째' }}
        {{ state_attr('weather.tempest_daily', 'forecast')[0].conditions | lower }}
        {%- if states('sensor.current_weather_hourly_next_precipitation_start') != 'unknown' -%}
          {%- if state_attr('weather.tempest_daily', 'forecast')[0].condition in ['rainy', 'lightning-rainy', 'lightning', 'hail', 'pouring', 'snowy-rainy' , 'snowy'] and (states('sensor.current_weather_hourly_next_precipitation_start')|as_datetime - now()).days < 1 -%}
            {{- ' with a '~state_attr('sensor.current_weather_hourly_next_precipitation_start','precipitation_probability') -}}%
            {{- ' chance of ' ~ state_attr('sensor.current_weather_hourly_next_precipitation_start','precip_type') }}
            {{ ' starting at ' ~ states('sensor.current_weather_hourly_next_precipitation_start') | as_datetime | as_local()| as_timestamp | timestamp_custom('%I:%M%p', default='') -}}
            {%if states('sensor.current_weather_hourly_next_precipitation_end') in ['unknown','unavailable'] %}
              {{''}}
            {%- else -%}
              {{ ' until ' ~ states('sensor.current_weather_hourly_next_precipitation_end') | as_datetime | as_local()| as_timestamp | timestamp_custom('%I:%M%p', default='') }}.
            {%- endif %}
          {%- else -%}
            {{ ' Next ' ~ state_attr('sensor.current_weather_hourly_next_precipitation_start','precip_type') ~ ' expected ' ~ states('sensor.current_weather_hourly_next_precipitation_start') | as_datetime | as_local()| as_timestamp | timestamp_custom('%a at %I:%M%p', default='') -}}
          {%- endif %}
        {%- else -%}
          {{ ' no precipitation expected today.' }}
        {%- endif %}
