---
binary_sensor:
  - name: "[Weather] High Temperature Alert"
    unique_id: weather_high_temperature_alert
    delay_on: 900
    delay_off: 900
    state: >
      {{ states('sensor.weather_temperature')|int
            > states('input_number.high_temperature_threshold')|int
          and is_state('input_boolean.alerts_weather','on') }}
    availability: "{{ is_number(states('sensor.weather_temperature')) }}"
    attributes:
      category: weather_alert

  - name: "[Weather] Low Temperature Alert"
    unique_id: weather_low_temperature_alert
    delay_on: 900
    delay_off: 900
    state: >
      {{ states('sensor.weather_temperature')|int
            < states('input_number.low_temperature_threshold')|int
          and is_state('input_boolean.alerts_weather','on') }}
    availability: "{{ is_number(states('sensor.weather_temperature')) }}"
    attributes:
      category: weather_alert

  - name: "[Weather] Temperature Alert"
    unique_id: temperature_alert
    icon: >
      {% if is_state('binary_sensor.high_temperature_alert','on') %} mdi:thermometer-alert
      {% elif is_state('binary_sensor.low_temperature_alert','on') %} mdi:thermometer-alert
      {% else %} mdi:thermometer
      {% endif %}
    state: >
      {{ is_state('binary_sensor.high_temperature_alert','on')
          or is_state('binary_sensor.low_temperature_alert','on') }}
    attributes:
      category: weather_alert
      type: >
        {% if is_state('binary_sensor.high_temperature_alert','on') %} Heat
        {% elif is_state('binary_sensor.low_temperature_alert','on') %} Cold
        {% else %} Off
        {% endif %}