---
sensor:
  - platform: rest
    name: adsb_aircraft_tracked
    unique_id: adsb_aircraft_tracked
    resource: http://192.168.1.132:8080/data/aircraft.json
    value_template: >
      {{ value_json.aircraft | length }}
    method: GET
    scan_interval: 15
    json_attributes:
      - now
      - aircraft
