---
# ADS-B System / Flightradar 24

binary_sensor:
  - platform: template
    sensors:
      adsb_fr24_feeder_receiver_connected:
        friendly_name: FR24 Receiver Connected
        value_template: '{{ is_state_attr("sensor.adsb_fr24_feeder", "rx_connected", "1") }}'
        device_class: connectivity
      adsb_fr24_feeder_link_connected:
        friendly_name: FR24 Link Connected
        value_template: '{{ is_state_attr("sensor.adsb_fr24_feeder", "feed_status", "connected") }}'
        device_class: connectivity
      adsb_fr24_mlat_connected:
        friendly_name: FR24 MLAT Connected
        value_template: '{{ is_state_attr("sensor.adsb_fr24_feeder", "mlat-ok", "OK") }}'
        device_class: connectivity

sensor:
  - platform: rest
    name: ADSB FR24 Feeder
    resource: http://192.168.1.65:8754/monitor.json
    value_template: "{{ value_json.feed_alias }}"
    method: GET
    scan_interval: 60
    json_attributes:
      - rx_connected
      - feed_status
      - d11_map_size
      - feed_num_ac_tracked
      - build_version
      - build_timestamp
      - feed_alias
      - mlat-ok
      - mlat-number-seen
      - last_rx_connect_time
      - feed_num_ac_adsb_tracked
      - feed_num_ac_non_adsb_tracked

  - platform: template
    sensors:
      adsb_fr24_feeder_radar_code:
        friendly_name: Radar Code
        icon_template: mdi:radar
        value_template: '{{ states.sensor.adsb_fr24_feeder.attributes["feed_alias"] }}'
      adsb_fr24_feeder_aircraft_tracked:
        friendly_name: Aircraft Tracked
        icon_template: mdi:airplane
        value_template: '{{ states.sensor.adsb_fr24_feeder.attributes["d11_map_size"] | round(0) }}'
        unit_of_measurement: "aircrafts"
      adsb_fr24_feeder_aircraft_uploaded:
        friendly_name: Aircraft Uploaded
        icon_template: mdi:airplane
        value_template: '{{ states.sensor.adsb_fr24_feeder.attributes["feed_num_ac_tracked"] | round(0) }}'
        unit_of_measurement: "aircrafts"
      adsb_fr24_feeder_version:
        friendly_name: Version
        icon_template: mdi:airplane
        value_template: '{{ states.sensor.adsb_fr24_feeder.attributes["build_version"] }}'
      adsb_fr24_feed_num_ac_adsb_tracked:
        friendly_name: ADSB Tracked
        icon_template: mdi:airplane
        value_template: '{{ states.sensor.adsb_fr24_feeder.attributes["feed_num_ac_adsb_tracked"] | round(0) }}'
        unit_of_measurement: "aircraft"
      adsb_fr24_feed_num_ac_non_adsb_tracked:
        friendly_name: Non ADS-B Tracked
        icon_template: mdi:airplane
        value_template: '{{ states.sensor.adsb_fr24_feeder.attributes["feed_num_ac_non_adsb_tracked"] | round(0) }}'
        unit_of_measurement: "aircraft"
