---
sensor:
  - platform: rest
    name: adsb_aircraft_tracked
    resource: http://192.168.1.65/data/aircraft.json
    value_template: "{{ value_json.messages }}"
    method: GET
    scan_interval: 15
    json_attributes:
      - now
      - aircraft
