---
resource: !secret lastfm_topalbums_url
sensor:
  name: lastfm_user_topalbums
  value_template: >
    {{ value_json.topalbums.album[0].artist.name}} - {{ value_json.topalbums.album[0].name }}
  json_attributes_path: $.topalbums
  json_attributes:
    - album
scan_interval: 600
