---
resource: !secret lastfm_topartists_url
sensor:
  name: lastfm_user_topartists
  value_template: >
    {{ value_json.topartists.artist[0].name}}
  json_attributes_path: $.topartists
  json_attributes:
    - artist
scan_interval: 600
