---
resource: !secret lastfm_bacco007_toptracks_url
sensor:
  name: lastfm_bacco007_user_toptracks
  value_template: >
    {{ value_json.toptracks.track[0].artist.name}} - {{ value_json.toptracks.track[0].name }}
  json_attributes_path: $.toptracks
  json_attributes:
    - track
scan_interval: 1200
