substitutions:
  name: "ble-proxy-office"
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

captive_portal:

web_server:
  port: 80
  include_internal: true
