---
trigger:
  - platform: calendar
    event: end
    entity_id: calendar.ical_indycar
  - platform: event
    event_type: event_template_reloaded
action:
  - service: calendar.list_events
    data:
      end_date_time: "{{now() + timedelta(days=365)}}"
    target:
      entity_id: calendar.ical_indycar
    response_variable: agenda
  - variables:
      all_events: "{{ agenda.events | list }}"
      next_5_events: "{{ agenda.events[:5] | list }}"
      dump: "{{agenda}}"
      countnumb: "{{agenda.events | count}}"
sensor:
  - name: "[Upcoming Sport] IndyCar"
    unique_id: upcoming_sport_indycar
    icon: "mdi:flag-checkered"
    picture: /local/sportlogos/indycar.png
    state: >
      {%- if countnumb == 0 %}
        Nothing Scheduled
      {%- else %}
        {%- from 'easy_time.jinja' import easy_relative_time %}
        {{next_5_events[0]['summary']}} @ {{next_5_events[0]['location']}} - {{ easy_relative_time(next_5_events[0]['start'], 'day, hour, minute') }} ({{ as_timestamp(next_5_events[0]['start'])|timestamp_custom ('%a %H:%M',0) }})
      {%- endif %}
    attributes:
      category: sport
      remaining_events: "{{countnumb}}"
      next_5_events: >
        {%- if countnumb == 0 %}
          No Events
        {%- else %}
          {{next_5_events}}
        {%- endif %}
      nextevent_timeto: >
        {%- if countnumb == 0 %}
          -999
        {%- else %}
          {{ ((as_timestamp(next_5_events[0]['start'])-as_timestamp(now())) | int/60/1440) | round (0) }}
        {%- endif %}
      nextevent_desc: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[0]['summary']}}
        {%- endif %}
      nextevent_locn: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[0]['location']}}
        {%- endif %}
      nextevent_time: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {%- from 'easy_time.jinja' import easy_relative_time %}
          {{ easy_relative_time(next_5_events[0]['start'], 'day, hour, minute') }} ({{ as_timestamp(next_5_events[0]['start'])|timestamp_custom ('%a %H:%M',0) }})
        {%- endif %}
      afterevent_desc: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[1]['summary']}}
        {%- endif %}
      afterevent_locn: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[1]['location']}}
        {%- endif %}
      afterevent_time: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {%- from 'easy_time.jinja' import easy_relative_time %}
          {{ easy_relative_time(next_5_events[1]['start'], 'day, hour, minute') }} ({{ as_timestamp(next_5_events[1]['start'])|timestamp_custom ('%a %H:%M',0) }})
        {%- endif %}
      afterevent_timeto: >
        {%- if countnumb == 0 %}
          -999
        {%- else %}
          {{ ((as_timestamp(next_5_events[1]['start'])-as_timestamp(now())) | int/60/1440) | round (0) }}
        {%- endif %}
